package domain

import (
	"strings"
	"testing"
)

// The checksum tests use numbers generated by the published algorithms rather
// than real documents. That is deliberate: a test suite is not a place to put
// somebody's actual Aadhaar number.

func TestVerhoeff_KnownVectors(t *testing.T) {
	// Verhoeff's own worked examples plus generated Aadhaar-shaped numbers.
	valid := []string{"2363", "758722", "234567890124", "223456789018", "987654321012"}
	for _, v := range valid {
		if !verhoeffValid(v) {
			t.Errorf("verhoeffValid(%q) = false, want true", v)
		}
	}
	invalid := []string{"2364", "758723", "234567890125", "223456789019"}
	for _, v := range invalid {
		if verhoeffValid(v) {
			t.Errorf("verhoeffValid(%q) = true, want false", v)
		}
	}
}

// TestVerhoeff_CatchesTransposition is the reason Aadhaar uses Verhoeff rather
// than a simpler digit sum: it catches adjacent transpositions, the single most
// common typing error, which a mod-10 sum does not.
func TestVerhoeff_CatchesTransposition(t *testing.T) {
	base := "234567890124"
	if !verhoeffValid(base) {
		t.Fatalf("fixture %q should be valid", base)
	}
	caught := 0
	for i := 0; i < len(base)-1; i++ {
		if base[i] == base[i+1] {
			continue // transposing equal digits is a no-op
		}
		b := []byte(base)
		b[i], b[i+1] = b[i+1], b[i]
		if !verhoeffValid(string(b)) {
			caught++
		} else {
			t.Errorf("transposition at %d (%q) passed the check digit", i, string(b))
		}
	}
	if caught == 0 {
		t.Fatal("no transpositions were tested")
	}
}

func TestLuhn_EmiratesID(t *testing.T) {
	if !luhnValid("784197012345670") {
		t.Error("valid Emirates ID rejected")
	}
	if luhnValid("784197012345671") {
		t.Error("Emirates ID with a wrong check digit accepted")
	}
}

func TestNRIC_CheckLetter(t *testing.T) {
	valid := []string{"S1234567D", "T0123456G", "F1234567N", "G1234567X"}
	for _, v := range valid {
		if !nricValid(v) {
			t.Errorf("nricValid(%q) = false, want true", v)
		}
	}
	if nricValid("S1234567A") {
		t.Error("NRIC with a wrong check letter accepted")
	}
}

// TestValidateDocumentNumber_PerCountry is the core of the global-profile
// promise: each country's own documents are accepted, and another country's
// are not silently waved through.
func TestValidateDocumentNumber_PerCountry(t *testing.T) {
	ok := []struct {
		country Country
		doc     DocumentType
		number  string
		want    string
	}{
		{"IN", DocAadhaar, "2345 6789 0124", "234567890124"},
		{"IN", DocAadhaar, "2345-6789-0124", "234567890124"},
		{"IN", DocPAN, "abcde1234f", "ABCDE1234F"},
		{"IN", DocPassport, "M1234567", "M1234567"},
		{"US", DocDriversLicense, "D1234567", "D1234567"},
		{"US", DocPassport, "512345678", "512345678"},
		{"GB", DocPassport, "123456789", "123456789"},
		{"AE", DocNationalID, "784-1970-1234567-0", "784197012345670"},
		{"SG", DocNationalID, "s1234567d", "S1234567D"},
		{"DE", DocPassport, "C01X00T47", "C01X00T47"},
	}
	for _, c := range ok {
		got, err := ValidateDocumentNumber(c.country, c.doc, c.number)
		if err != nil {
			t.Errorf("%s/%s %q: unexpected error %v", c.country, c.doc, c.number, err)
			continue
		}
		if got != c.want {
			t.Errorf("%s/%s %q normalised to %q, want %q", c.country, c.doc, c.number, got, c.want)
		}
	}

	bad := []struct {
		name    string
		country Country
		doc     DocumentType
		number  string
	}{
		{"aadhaar starting 1", "IN", DocAadhaar, "134567890123"},
		{"aadhaar bad check digit", "IN", DocAadhaar, "234567890125"},
		{"aadhaar too short", "IN", DocAadhaar, "23456789012"},
		{"pan wrong shape", "IN", DocPAN, "ABC1234EF"},
		{"emirates bad check", "AE", DocNationalID, "784197012345671"},
		{"nric bad letter", "SG", DocNationalID, "S1234567A"},
		{"empty", "US", DocPassport, ""},
		{"garbage", "US", DocPassport, "not-a-passport"},
		{"country has no such document", "US", DocAadhaar, "234567890124"},
		{"unsupported country", "ZZ", DocPassport, "123456789"},
	}
	for _, c := range bad {
		if _, err := ValidateDocumentNumber(c.country, c.doc, c.number); err == nil {
			t.Errorf("%s: %s/%s %q was accepted, want an error", c.name, c.country, c.doc, c.number)
		}
	}
}

// TestValidationErrorsAreActionable: a desk agent reading the error should know
// what to retype. "invalid input" is not a usable message at a check-in counter.
func TestValidationErrorsAreActionable(t *testing.T) {
	_, err := ValidateDocumentNumber("IN", DocAadhaar, "134567890123")
	if err == nil {
		t.Fatal("expected an error")
	}
	if !strings.Contains(err.Error(), "Aadhaar") {
		t.Errorf("error does not name the document: %v", err)
	}

	_, err = ValidateDocumentNumber("US", DocAadhaar, "234567890124")
	if err == nil {
		t.Fatal("expected an error")
	}
	// Should say what the US *does* accept, not just what it rejected.
	if !strings.Contains(err.Error(), "Passport") {
		t.Errorf("error should list the accepted documents, got: %v", err)
	}
}

// TestHashDocument_IsStableAndScoped: the same number always resolves to the
// same profile, and the same digits from different authorities never collide.
func TestHashDocument_IsStableAndScoped(t *testing.T) {
	key := []byte("test-key")

	a := HashDocument(key, "IN", DocAadhaar, "234567890124")
	b := HashDocument(key, "IN", DocAadhaar, "234567890124")
	if a != b {
		t.Error("the same document must hash identically, or a returning guest opens a second file")
	}

	// Same digits, different country.
	if HashDocument(key, "GB", DocPassport, "123456789") == HashDocument(key, "US", DocPassport, "123456789") {
		t.Error("identical numbers from different countries must not collide into one person")
	}
	// Same digits, different document type.
	if HashDocument(key, "IN", DocPassport, "M1234567") == HashDocument(key, "IN", DocNationalID, "M1234567") {
		t.Error("identical numbers of different document types must not collide")
	}
	// Different key, different hash — a stolen table is inert without the key.
	if HashDocument([]byte("other-key"), "IN", DocAadhaar, "234567890124") == a {
		t.Error("the hash must depend on the key")
	}
	// The number must not be recoverable from the stored value.
	if strings.Contains(a, "234567890124") {
		t.Error("the raw number leaked into the hash")
	}
}

func TestLast4(t *testing.T) {
	if got := Last4("234567890124"); got != "0124" {
		t.Errorf("Last4 = %q, want 0124", got)
	}
	if got := Last4("abc"); got != "abc" {
		t.Errorf("Last4 of a short number = %q, want abc", got)
	}
}

// TestPortability is the cross-border mechanism. A domestic document opens a
// file at home; only a portable one lets another country's hotels find it.
func TestPortability(t *testing.T) {
	cases := []struct {
		country Country
		doc     DocumentType
		want    bool
	}{
		{"IN", DocPassport, true},
		{"IN", DocAadhaar, false},
		{"IN", DocPAN, false},
		{"US", DocPassport, true},
		{"US", DocDriversLicense, false},
		{"SG", DocPassport, true},
		{"SG", DocNationalID, false},
	}
	for _, c := range cases {
		d := IdentityDocument{Country: c.country, Type: c.doc}
		if got := d.Portable(); got != c.want {
			t.Errorf("%s/%s portable = %v, want %v", c.country, c.doc, got, c.want)
		}
	}
}

// TestEveryCountryHasAPortableDocument: without one, a guest from that country
// could open a file at home and then be unreachable everywhere else, which
// defeats the entire point of a global bureau.
func TestEveryCountryHasAPortableDocument(t *testing.T) {
	for _, rules := range SupportedCountries() {
		portable := false
		for _, d := range rules.Documents {
			if d.Portable {
				portable = true
			}
		}
		if !portable {
			t.Errorf("%s (%s) has no portable document, so its guests could never be resolved abroad",
				rules.Name, rules.Country)
		}
	}
}

// TestRestrictedDocumentsAreMarked: the ones carrying statutory storage limits
// must be flagged so the API and UI can treat them accordingly.
func TestRestrictedDocumentsAreMarked(t *testing.T) {
	in, ok := RulesFor("IN")
	if !ok {
		t.Fatal("India should be supported")
	}
	for _, d := range in.Documents {
		if d.Type == DocAadhaar {
			if !d.Restricted {
				t.Error("Aadhaar must be marked restricted — its storage is limited by statute")
			}
			if d.Note == "" {
				t.Error("a restricted document should explain the restriction")
			}
			return
		}
	}
	t.Fatal("Aadhaar not found in the India rules")
}

func TestSupportedCountries_AreOrderedAndComplete(t *testing.T) {
	cs := SupportedCountries()
	if len(cs) < 5 {
		t.Fatalf("only %d countries registered", len(cs))
	}
	for i := 1; i < len(cs); i++ {
		if cs[i].Country < cs[i-1].Country {
			t.Errorf("countries are not in stable order: %s before %s", cs[i-1].Country, cs[i].Country)
		}
	}
	for _, c := range cs {
		if c.Name == "" || len(c.Documents) == 0 {
			t.Errorf("%s is registered but incomplete", c.Country)
		}
		for _, d := range c.Documents {
			if d.Authority == "" {
				t.Errorf("%s/%s has no issuing authority — nothing could verify it", c.Country, d.Type)
			}
			if d.Example == "" {
				t.Errorf("%s/%s has no example, so the error message cannot show a format", c.Country, d.Type)
			}
			// Every published example must satisfy its own pattern and checksum.
			if _, err := ValidateDocumentNumber(c.Country, d.Type, d.Example); err != nil {
				t.Errorf("%s/%s published example %q fails its own validation: %v",
					c.Country, d.Type, d.Example, err)
			}
		}
	}
}
